### ISSUE TITLE
Logger modifies root logger

### ISSUE THREAD

**Issue by TheGreatAlgo** [erdogant/colourmap#2]
https://github.com/erdogant/colourmap/blob/82c7600b3d4095eac347f5182e28beba835f54ae/colourmap/colourmap.py#L16

This accesses the root logger and modifies it so when I import distfit which imports this, my logs become corrupted with the format defined here.

Issue similar to this https://github.com/erdogant/clustimage/issues/22

fixed by https://github.com/erdogant/colourmap/pull/1

**Comment by erdogant** [comment]
Thank you for your contribution! I created a new version.
Update to the latest version with `pip install -U colourmap`
